version: '3.9'
services:
  postgres_dev:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: citizix_user
      POSTGRES_DB: citizix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  postgres_dev_data: